@host = http://localhost:7071/api

# @name healthCheck
HEAD {{host}}/todos

###

# @name getTodos
GET {{host}}/todos

###

# @name createTodo
POST {{host}}/todos
Content-Type: application/json

{
    "owner": "Aaron",
    "description": "Hello ServerlessDays ANZ"
}

###

# @name getNewlyCreatedTodo
@todoId = {{createTodo.response.body.$.id}}
GET {{host}}/todos/{{todoId}}

###

# @name updateTodo
PUT {{host}}/todos/{{todoId}}
Content-Type: application/json

{
    "status": true
}

###

# @name getUpdatedTodo
GET {{host}}/todos

###

# @name deleteTodo
DELETE {{host}}/todos/{{todoId}}